// This code was initially generated by ServiceFoundry
// This code was initially generated by ServiceFoundry
// Copyright 2004-present Facebook. All Rights Reserved.

#include "logdevice/scribe/ScribeServiceHandler.h"

namespace facebook {
namespace scribe {

ScribeServiceHandler::ScribeServiceHandler() : FacebookBase2("Scribe") {
  taps_["stout"].name = "Guiness";
  taps_["stout"].color = BeerColor::Black;
  taps_["stout"].price_per_litre = 8.2;
  taps_["stout"].abv = 4.0;

  taps_["lager"].name = "Brooklyn";
  taps_["lager"].color = BeerColor::Yellow;
  taps_["lager"].price_per_litre = 6.3;
  taps_["lager"].abv = 4.0;

  taps_["double IPA"].name = "Boomsauce";
  taps_["double IPA"].color = BeerColor::Brown;
  taps_["double IPA"].price_per_litre = 5.6;
  taps_["double IPA"].abv = 5.0;
}

void ScribeServiceHandler::menu(
    std::vector<::facebook::scribe::Beer>& result) {
  for (auto kv : taps_) {
    result.push_back(kv.second);
  }
}

void ScribeServiceHandler::order(
    std::vector<::facebook::scribe::Beer>& result,
    std::unique_ptr<std::vector<std::string>> names) {
  for (auto it = names->begin(); it != names->end(); ++it) {
    result.push_back(taps_[*it]);
  }
}

facebook::fb303::cpp2::fb_status ScribeServiceHandler::getStatus() {
  return facebook::fb303::cpp2::fb_status::ALIVE;
}

} // namespace scribe
} // namespace facebook
