// This code was initially generated by ServiceFoundry
// Copyright 2004-present Facebook. All Rights Reserved.

#pragma once

#include "common/fb303/cpp/FacebookBase2.h"
#include "logdevice/scribe/if/gen-cpp2/ScribeService.h"

namespace facebook {
namespace scribe {

/**
 * TODO: Documentation
 */
class ScribeServiceHandler : virtual public ScribeServiceSvIf,
                             public facebook::fb303::FacebookBase2 {
 public:
  ScribeServiceHandler();

  void menu(std::vector<::facebook::scribe::Beer>& result) override;

  void order(
      std::vector<::facebook::scribe::Beer>& result,
      std::unique_ptr<std::vector<std::string>> names) override;

  facebook::fb303::cpp2::fb_status getStatus() override;

 private:
  std::map<std::string, ::facebook::scribe::Beer> taps_;
};

} // namespace scribe
} // namespace facebook
