FROM ubuntu:bionic

MAINTAINER Ahmed Soliman <asoli@fb.com>

ARG PARALLEL=4

RUN echo "/usr/local/lib" >> /etc/ld.so.conf && ldconfig

COPY logdevice/build_tools/ubuntu.deps /tmp/

RUN apt-get update && \
    apt-get install -y $(cat /tmp/ubuntu.deps) && \
    rm -rf /var/lib/apt/lists/*

COPY logdevice logdevice

RUN mkdir /build && cd /build && \
    cmake /logdevice/ && \
    make -j$PARALLEL && \
    cp /build/bin/ld* /usr/local/bin/ && \
    cp /build/bin/ld-dev-cluster /usr/local/bin/

WORKDIR /build

ENV LOGDEVICE_TEST_BINARY=/build/bin/logdeviced

CMD /bin/bash
