// This code was initially generated by ServiceFoundry
namespace cpp2 facebook.scribe
namespace py logdevice.scribe.scribe
namespace py3 logdevice.scribe

include "common/fb303/if/fb303.thrift"

enum BeerColor {
  Yellow = 1;
  Amber = 2;
  Brown = 3;
  Black = 4;
}

struct Beer {
  1: string name;
  2: BeerColor color;
  3: double price_per_litre;
  4: double abv;
}

exception CutoffException {
  1: string reason;
}

service ScribeService extends fb303.FacebookService {
  list<Beer> menu();
  list<Beer> order(
    1: list<string> names;
  ) throws (
    1: CutoffException ex;
  );
}
