// This code was initially generated by ServiceFoundry
// Copyright 2004-present Facebook. All Rights Reserved.

#include <gtest/gtest.h>

#include "logdevice/scribe/ScribeServiceHandler.h"

class ScribeTest : public ::testing::Test {
 protected:
  ScribeTest() {}

  void SetUp() override {
    // Put test case initialization code here
  }
};

namespace facebook {
namespace scribe {

TEST_F(ScribeTest, MenuTest) {
  ScribeServiceHandler handler;
  std::vector<Beer> response;
  handler.menu(response);
  EXPECT_EQ(3, response.size());
}

TEST_F(ScribeTest, OrderTest) {
  ScribeServiceHandler handler;
  std::vector<Beer> response;
  auto names = std::make_unique<std::vector<std::string>>();
  names->push_back("double IPA");
  handler.order(response, std::move(names));
  EXPECT_EQ("Boomsauce", response[0].name);
}

} // namespace scribe
} // namespace facebook
