#!/usr/bin/env python3

# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

class NodesConfigurationManagerParseException(Exception): ...
class NodesConfigurationManagerApiException(Exception): ...

def get_nodes_configuration(): ...
def nodes_configuration_to_json(): ...
def json_to_nodes_configuration(): ...
def overwrite_nodes_configuration(): ...
def update_server_config_with_nodes_configuration(): ...
def nodes_configuration_from_server_config(): ...
def provision_empty_nodes_configuration(): ...
def provision_initial_nodes_configuration(server_config: str): ...
def nodes_configuration_exists(server_config: str): ...
